# Numpy

numpy(numeric python) adalah sebuah library yang biasa digunakan untuk data science dan machine learning. Numpy digunakan karena kemudahannya dalam melakukan operasi matematika khusunya matriks

untuk menggunakannya kita harus menambahkan code:
    - import numpy

In [2]:
import numpy as np

numpy memiliki bentuk yang mirip dengan list, namun ada beberapa perbedaan:
    - numpy hanya terdiri dari 1 tipe value yang sama
    - jika kita print tipe numpy maka akan seperti list namun tanpa tanda koma

In [3]:
a = np.array([1,2,3])
b = [1,2,3]

In [7]:
print(a)

[1 2 3]


In [8]:
print(b)

[1, 2, 3]


In [9]:
c = [10, 8.5, "hello"]
d = np.array([10, 8.5, "hello"])

In [10]:
c

[10, 8.5, 'hello']

In [11]:
d

array(['10', '8.5', 'hello'], dtype='<U32')

urutan prioritas tipe dalam numpy array:
    1. string
    2. float
    3. integer

In [5]:
e = np.array([10, 11, 2.5])

In [14]:
e

array([10. , 11. ,  2.5])

In [8]:
a = np.array([3,5,7,8])
a

array([3, 5, 7, 8])

In [10]:
type(a)

numpy.ndarray

In [13]:
b = np.array([[2,5],[3,4]])
b

array([[2, 5],
       [3, 4]])

In [15]:
b.shape

(2, 2)

In [16]:
b = np.array([[2,5,6],[3,4,10]])
b

array([[ 2,  5,  6],
       [ 3,  4, 10]])

In [17]:
b.shape

(2, 3)

In [18]:
b[0]

array([2, 5, 6])

In [19]:
b[0][1]

5

In [20]:
b[1][2]

10

In [22]:
bb = np.array([[2,5],[3,4,7]])
bb

array([list([2, 5]), list([3, 4, 7])], dtype=object)

In [23]:
bb[0]

[2, 5]

In [24]:
bb[1][2]

7

In [41]:
a = np.array([3,5,6])
b = np.array([8,1,2])

In [27]:
a+b

array([11,  6,  8])

In [28]:
a+(2*b)

array([19,  7, 10])

In [29]:
a-b

array([-5,  4,  4])

In [31]:
2*b

array([16,  2,  4])

In [42]:
a*b

array([24,  5, 12])

In [32]:
c = np.array([3,5,6])
d = np.array([8,1,])
c+d

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [33]:
len(c)

3

In [43]:
a = np.array([1,2,3,6,4,0,10,7,8,9])

In [44]:
a

array([ 1,  2,  3,  6,  4,  0, 10,  7,  8,  9])

In [45]:
len(a)

10

In [46]:
a.min()

0

In [47]:
a.max()

10

In [48]:
a.mean()

5.0

more advance

In [50]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [51]:
a.shape

(2, 2)

In [52]:
b = np.array([[2,5],[9,1]])
b

array([[2, 5],
       [9, 1]])

In [54]:
a.dot(b) #perkalian matriks

array([[20,  7],
       [42, 19]])

In [55]:
a

array([[1, 2],
       [3, 4]])

In [57]:
c = np.array([5,6,7,8,9,10])
c

array([ 5,  6,  7,  8,  9, 10])

In [58]:
a.dot(c)

ValueError: shapes (2,2) and (6,) not aligned: 2 (dim 1) != 6 (dim 0)

In [59]:
#ingat aturan perkalian matriks

In [60]:
#c harus diubah ordonya dengan reshape

In [62]:
c = c.reshape(2,3) #len(c) = 6, maka ordo barunya 2x3 (2x3 = 6)
c

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [63]:
a.dot(c)

array([[21, 24, 27],
       [47, 54, 61]])

In [64]:
a.shape

(2, 2)

In [65]:
c.shape

(2, 3)

In [66]:
c.dot(a)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [67]:
#c bisa ditranspose

In [71]:
c = c.transpose()
c

array([[ 5,  8],
       [ 6,  9],
       [ 7, 10]])

In [72]:
c.dot(a)

array([[29, 42],
       [33, 48],
       [37, 54]])

In [73]:
c.shape

(3, 2)